---
name: portainer-agent
services:
  portainer-agent:
    image: docker.io/portainer/agent:2.27.7-alpine
    container_name: portainer-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - '0.0.0.0:9001:9001'
    restart: unless-stopped
