---
name: KICS

permissions: {}

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  test:
    name: KICS Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read # checkout
      security-events: write # upload SARIF to code scanning
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - name: Mkdir results-dir
        run: mkdir -p results-dir
      - name: run kics Scan
        uses: checkmarx/kics-github-action@05aa5eb70eede1355220f4ca5238d96b397e30a6 # v2.1.20
        with:
          path: "."
          ignore_on_exit: results
          output_path: results-dir
          output_formats: "json,sarif"
      - name: Upload SARIF to code scanning
        if: always()
        uses: github/codeql-action/upload-sarif@db488ddef3bf6cb639b32c2e9a7c0a7ea8271d28 # v4.37.8
        with:
          sarif_file: results-dir/results.sarif
          category: kics
