---
name: KICS

permissions: read-all

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Mkdir results-dir
        run: mkdir -p results-dir
      - name: run kics Scan
        uses: checkmarx/kics-github-action@v2.1.20
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: "."
          ignore_on_exit: results
          enable_comments: true
          output_path: results-dir
          output_formats: "json,sarif"
      - name: Show results
        run: |
          cat results-dir/results.sarif
          cat results-dir/results.json
